### ISSUE TITLE
Provide a binary search similar to what the ",bin <some_binary>" bot used to do

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixos-search#420] opened 2022-01-23 23:06 UTC
**Introduce your stance**

More often than not, I don't need the package search so much as an easy way to find out, "oh gosh, where do I get `iconv` from?".

It would be great if there were another tab in the UI that provided a way to locate binaries in their nixpkg pkg.

**Comment by garbas** [comment] 2022-01-24 11:32
Duplicate of #104

**Closed by garbas** 2022-01-24 11:32 UTC
