### ISSUE TITLE
a way to see what outputs a package has

### ISSUE THREAD

**Issue by Artturin** [NixOS/nixos-search#375] opened 2021-11-24 02:00 UTC
Would help with cases such as https://github.com/NixOS/nixpkgs/issues/147215

**Comment by googleson78** [comment] 2022-03-24 10:18
Duplicate of #302

**Comment by ncfavier** [comment] 2022-03-24 10:20
This was done in https://github.com/NixOS/nixos-search/pull/419, I forgot to search for other open issues :)

**Closed by ncfavier** 2022-03-24 10:20 UTC
Labels: enhancement

**Comment by ncfavier** [comment] 2022-03-24 10:21
Also note https://github.com/NixOS/nixos-search/pull/452
