### ISSUE TITLE
services.nginx.config: questionsmarks are being displayed instead of exceptions

### ISSUE THREAD

**Issue by madonius** [NixOS/nixos-search#313] opened 2021-06-05 15:37 UTC
Hi, as described, in the options search page for `services.nginx.config` questionmarks are being displayed instead of exceptions this configuration is not colliding with.
See:
![image](https://user-images.githubusercontent.com/1246752/120897040-9f612c00-c624-11eb-8000-5d84553e7da5.png)

**Comment by ncfavier** [comment] 2021-12-26 15:42
Duplicate of #303, point 1.

**Closed by ncfavier** 2021-12-26 15:42 UTC
