### ISSUE TITLE
string examples not formatted correctly on search.nixos.org

### ISSUE THREAD

**Issue by DavHau** [NixOS/nixos-search#198] opened 2020-09-24 04:21 UTC
For example the example for [system.activationScripts](https://search.nixos.org/options?show=system.activationScripts&query=activation&from=0&size=30&sort=relevance&channel=unstable#disabled) is formatted incorrectly and quite difficult to read.

**Comment by garbas** [comment] 2020-09-24 12:43
duplicate of #175

**Closed by garbas** 2020-09-24 12:43 UTC
Labels: bug, duplicate
