### ISSUE TITLE
korganizer wrongly shows up as a QT library

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixos-search#563] opened 2022-11-04 12:25 UTC
For [this search query](https://search.nixos.org/packages?channel=22.05&from=0&size=50&sort=relevance&type=packages&query=korganizer), the following is shown:

![image](https://user-images.githubusercontent.com/1663259/199972078-f6014ffc-f357-493e-ad0e-1eba587dfc8e.png)

... however, the correct attribute is actually just `korganizer` in the root of nixpkgs, which isn't shown in the search results at all.

**Comment by ncfavier** [comment] 2022-11-04 12:33
This is another consequence of https://github.com/NixOS/nixos-search/issues/345#issuecomment-1079286996. Closing as duplicate of that issue.

**Closed by ncfavier** 2022-11-04 12:33 UTC

**Comment by ncfavier** [comment] 2022-11-04 12:38
To clarify, this is because `korganizer` and `libsForQt5.korganizer` are the same derivation, so only one of them is shown. `korganizer` isn't any more correct than `libsForQt5.korganizer` as far as nixpkgs is concerned, but it might be more convenient (and it should definitely be shown).
