### ISSUE TITLE
The old way of searching for a package or option was easier than this new one!

### ISSUE THREAD

**Issue by alciono** [NixOS/nixos-search#180] opened 2020-09-04 09:24 UTC
Hello,

After trying and testing a few dozen Linux distros over the years, I have been enjoying the exclusive usage of NIXOS for about five years and still couldn't find anything better so far.

Is it still possible to use the new NIXOS package/option search tool the way it used to be?
I found the previous way very simple and effective as it gave  quick and accurate results every single time.
Out of  frustrations I am still struggling trying to achieve the same outcome from this current version to a point that I, and probably many others, would be pleased to know why it had to be changed.
As the search function is more than likely used very often by most visitors of the NIXOS packages/options  pages do you think it would be possible to get back to a search as user friendly as it used to be?
I don't know how it would  be possible to improve the previous version but, as far as I am concerned, it was already a delight to use it the way it was without feeling the need of modifying anything.

I just hope that my frustration is coming from my inability to use this new tool properly...

Many thanks for all your efforts,

Alci

**Comment by garbas** [comment] 2020-09-04 17:15
While the search was working for you it wasn't working for others, You can actually look in nixos-homepage reposiotry how many search related issues we addressed.

The previous search was designed to load all of the packages as JSON which prevented us actually to search over all of the packages, but only the "selected" ones. Going forward the problem will only increase since we will have to support many more repositories (eg. with flakes).

We will improve the current search as we go forward. I would suggest helping us with queries that didn't yield results as you expected, either the order being wrong or items missing from the list. Many more improvements are on the way - as you can see in the issue tracker - and I hope with time we can change your mind.

Again thank you for the report.

(closing the issue since there is nothing actionable from it)

**Closed by garbas** 2020-09-04 17:15 UTC
