### ISSUE TITLE
Searching for options have inconsistent behaviour 

### ISSUE THREAD

**Issue by praduca** [NixOS/nixos-search#251] opened 2020-12-07 22:13 UTC
When selecting options for 20.09 or unstable sometimes you get a list of options, sometimes none is returned.
I can always get results for 20.03, but for 20.09 i could get results only one time, and never for unstable (i'm not on unstable so just query unstable for testing right now)

**Comment by colemickens** [comment] 2020-12-08 02:29
It's not working at all for me, now.

**Comment by garbas** [comment] 2020-12-08 07:07
@colemickens @praduca since a week or so we are experiencing this problem (since we merged #239). The problem is intermittent and hard to reproduce locally. Anyway, this is going to be fixed today, either by reverting #239 or doing #239 properly.

But thank you a lot for reporting. If nothing I can see that somebody is really using https://search.nixos.org :)

**Closed by garbas** 2020-12-08 07:07 UTC
