### ISSUE TITLE
Package search is very confusing now

### ISSUE THREAD

**Issue by ToxicFrog** [NixOS/nixos-search#191] opened 2020-09-15 11:40 UTC
Specifically, searching for a specific package, especially if it has non-alphanumerics in the name, tends to return lots of unrelated results.

For example:
- A search for `munin` returns one result, munin itself
- A search for `contrib` returns 103 results. Not all of them have "contrib" in the name but the ones that don't appear to have it in the description, so that's ok (although a "search in description y/n" option would be nice)
- A search for `munin contrib` returns no results; presumably it's searching for (`munin` and `contrib`), which is the behaviour I expect.
- A search for `munin-contrib` (the actual package I was looking for) returns...40 results? It's clearly not the same as (`munin` or `contrib`), but it's not (`munin` and `contrib`) either, or `munin-contrib` as a single string (which is what I actually wanted)

This appears to have been introduced quite recently, possibly at the same time as the new "fuzzy" search.

**Comment by Zopieux** [comment] 2020-09-15 21:11
That looks like an exact duplicate of #187, although your examples are more generic than the `<placeholder>` issue.
The ElasticSearch query is done on a tokenized versions of package names and options, which means munin-contrib will be indexed as munin-contrib, munin, contrib, as well as other variants such as the reversed strings (birtnoc, …). Add the fuzziness tolerance on top of that, and indeed the results become much noisier – though they allow for typos and such.

Coming up with a good search scoring is tricky – no wonders why Google has little competition. I don't want to diminish the work that went into this, clearly @garbas wants to help people finding relevant packages & options, even when they have typos etc. But I believe we can agree the current scoring is too lax to be considered an improvement over the previous "dumber" version.

Maybe a stopgap solution would be to give a very strong weight to exact matches and add a "cut-off" score threshold under which no results are returned, to reduce the perceived noise.

**Comment by ToxicFrog** [comment] 2020-09-16 02:29
Honestly, I would be very happy with just two new options:
- exact substring search only, no fuzziness, no tokenization
- search in descriptions as well as package names y/n

**Comment by garbas** [comment] 2020-09-16 21:55
@ToxicFrog Thank you! this is an awesome report

>     * A search for `munin-contrib` (the actual package I was looking for) returns...40 results? It's clearly not the same as (`munin` or `contrib`), but it's not (`munin` and `contrib`) either, or `munin-contrib` as a single string (which is what I actually wanted)
> 
> 
> This appears to have been introduced quite recently, possibly at the same time as the new "fuzzy" search.

This is nothing to do with fuzziness but I think ElasticSearch does something to the query, I'll take a look at it tomorrow.

**Closed** 2020-09-17 16:00 UTC
Labels: bug, prio:high
